# Site settings
title: Royal'blog
SEOTitle: Royal Blog
header-img: img/home-bg.jpg
email: pengqinping@gmail.com
description: ""
keyword: "Android"
url: "http://pengqinping.github.io/Royal-Blogs"              # your host, for absolute URL
baseurl: ""    # for example, '/blog' if your blog hosted on 'host/blog'
#BASE_PATH :  http://pengqinping.github.io/Blogs


# SNS settings
RSS: false
weibo_username:     pengqinping
zhihu_username:     pengqinping
github_username:    pengqinping
#twitter_username:  huxpro
facebook_username:  pengqinping



# Build settings
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
gems: [jekyll-paginate]


# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
disqus_username: pengqinping

# Duoshuo settings
#duoshuo_username: huxblog
# Share component is depend on Comment so we can NOT use share only.
# duoshuo_share: true                     # set to false if you want to use Comment without Sharing



# Analytics settings
# Baidu Analytics
#ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics
#ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
#ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "如果写代码都做不好，还能做好什么，生命不息，奋斗不止。"
sidebar-avatar: /img/avatar-pqp.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "Hux Blog",
        href: "http://huangxuan.me"
    }
#    ,{
#         title: "Foo",
#         href: "#"
#    },{
#        title: "Bar",
#        href: "#"
#   },{
#        title: "Example Friends",
#        href: "#"
#    },{
#        title: "It helps SEO",
#        href: "#"
#    }
]
